baseurl: "/Haal-Centraal-BAG-bevragen"
apiname: "BAG Bevragen"
url: "http://localhost:4000"
nav:
  - title: BAG Bevragen
    subnav:
      - title: Home
        path: /
        subpath: /
      - title: Getting started
        path: /getting-started
        subpath: /getting-started.html
      - title: User stories
        url: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues?q=is%3Aopen+is%3Aissue+label%3A%22user+story%22
        subpath: /user-stories.html
        target: blank
#      - title: Goals canvas
#        path: /getting-started
#        subpath: /goals-canvas.html
  - title: Specificaties
    subnav:
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui
        subpath: /swagger-ui.html
      - title: Bevragen API (redoc)
        path: /redoc
        subpath: /redoc.html
      - title: Features
        path: /features
        subpath: /features.html