baseurl: "/Haal-Centraal-BAG-bevragen"
apiname: "BAG Bevragen"
url: "http://localhost:4000"
nav:
  - title: BAG Bevragen
    subnav:
      - title: Home
        path: /
      - title: Getting started
        path: /getting-started
      - title: User stories
        url: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues?q=is%3Aopen+is%3Aissue+label%3A%22user+story%22
        path: /user-stories
        target: blank
#      - title: Goals canvas
#        path: /getting-started
  - title: Specificaties
    subnav:
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui
      - title: Bevragen API (redoc)
        path: /redoc
      - title: Features
        path: /features
